# Generated by Django 6.0.3 on 2026-03-25 16:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('color_urgencia', models.BooleanField(default=False, help_text='Si está marcado, será rojo. Si no, azul.')),
                ('mostrar', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarreraPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo_carrera', models.CharField(default='Carrera Odontología', max_length=255)),
                ('plan_estudios', wagtail.fields.StreamField([('titulo_anio', 0), ('subtitulo_periodo', 1), ('materia', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título de Año'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo de Periodo'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Código', 'max_length': 10, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Nombre de la materia', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Periodicidad (Ej: 1er C.)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('codigo', 2), ('nombre', 3), ('periodicidad', 4)]], {'label': 'Materia'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FolpHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('carrusel', 5), ('accesos_rapidos', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('imagen', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'template': 'facultad/blocks/hero_slider.html'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('imagen_logo', 6), ('etiqueta', 7), ('url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'template': 'facultad/blocks/accesos_rapidos.html'})})),
            ],
            options={
                'verbose_name': 'Página de Inicio FOLP',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('video_url', models.URLField(help_text='Pegá el link de YouTube')),
                ('prioridad', models.IntegerField(default=10)),
                ('ancho', models.CharField(choices=[('col-md-4', 'Chica'), ('col-md-8', 'Mediana'), ('col-12', 'Grande')], default='col-md-4', max_length=20)),
            ],
            options={
                'verbose_name': 'Video para la Home',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticiaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fecha', models.DateField(verbose_name='Fecha de publicación')),
                ('resumen', models.CharField(max_length=250)),
                ('cuerpo', wagtail.fields.RichTextField(blank=True)),
                ('prioridad', models.IntegerField(default=10)),
                ('ancho', models.CharField(choices=[('col-md-4', 'Chica'), ('col-md-8', 'Mediana'), ('col-12', 'Grande')], default='col-md-4', max_length=20)),
                ('mostrar_texto_en_home', models.BooleanField(default=True)),
                ('convertir_en_popup', models.BooleanField(default=False)),
                ('elementos_extra', wagtail.fields.StreamField([('p', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {})}, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Pegá acá el link de YouTube (ej: https://www.youtube.com/watch?v=...) para que aparezca al final de la noticia.', null=True)),
                ('boton_accion', wagtail.fields.StreamField([('boton', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('texto', 0), ('archivo', 1), ('url_externa', 2), ('icono_fontawesome', 3), ('imagen_logo', 4)]], {})})),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('link_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PaginaEstandar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitulo', models.CharField(blank=True, max_length=250)),
                ('video_url', models.URLField(blank=True, help_text='Link de YouTube', null=True)),
                ('cuerpo', wagtail.fields.RichTextField(blank=True)),
                ('boton_accion', wagtail.fields.StreamField([('boton', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('texto', 0), ('url_o_archivo', 1), ('documento', 2), ('icono_fontawesome', 0), ('imagen_logo', 3)]], {})})),
                ('imagen_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
