# Generated by Django 6.0.3 on 2026-03-11 12:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolpHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 5), ('accesos_rapidos', 11), ('contenido_libre', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título llamativo', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Ver más', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('imagen', 2), ('link_texto', 3), ('link_url', 4)]], {'template': 'facultad/blocks/hero_slider.html'}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Clase de FontAwesome, ej: fa-tooth'}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.BooleanBlock', (), {'help_text': '¿Usar color cian médico?', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('icono', 6), ('etiqueta', 7), ('url', 8), ('color_destacado', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'template': 'facultad/blocks/accesos_rapidos.html'}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul'], 'template': 'facultad/blocks/texto_libre.html'})})),
            ],
            options={
                'verbose_name': 'Página de Inicio FOLP',
            },
            bases=('wagtailcore.page',),
        ),
    ]
