# Generated by Django 6.0.3 on 2026-03-11 12:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folphomepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 3), ('accesos_rapidos', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('imagen', 2)]], {'template': 'facultad/blocks/hero_slider.html'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ej: fa-tooth'}), 5: ('wagtail.blocks.URLBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('icono', 4), ('etiqueta', 0), ('url', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'template': 'facultad/blocks/accesos_rapidos.html'})}),
        ),
        migrations.CreateModel(
            name='NoticiaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fecha', models.DateField(verbose_name='Fecha de publicación')),
                ('resumen', models.CharField(max_length=250)),
                ('cuerpo', wagtail.fields.RichTextField()),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
