# Generated by Django 6.0.3 on 2026-04-01 12:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0002_noticiasblogpage_alter_noticiapage_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiasblogpage',
            name='color_seccion',
            field=models.CharField(choices=[('verde', 'Verde'), ('azul', 'Azul')], default='verde', max_length=20),
        ),
        migrations.CreateModel(
            name='BlogPageRelatedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facultad.noticiapage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_news', to='facultad.noticiasblogpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
