# Generated by Django 6.0.3 on 2026-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0002_alter_folphomepage_body_noticiapage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('color_urgencia', models.BooleanField(default=False, help_text='Si está marcado, será rojo. Si no, azul.')),
                ('mostrar', models.BooleanField(default=True)),
            ],
        ),
    ]
