# Generated by Django 6.0.3 on 2026-04-01 12:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0003_noticiasblogpage_color_seccion_blogpagerelatednews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiapage',
            name='elementos_extra',
        ),
        migrations.AddField(
            model_name='paginaestandar',
            name='cuerpo_tecnicaturas',
            field=wagtail.fields.StreamField([('tecnicatura', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('btn-dark-green', 'Verde Oscuro'), ('btn-light-green', 'Verde Claro'), ('btn-gray', 'Gris')]}), 5: ('wagtail.blocks.StructBlock', [[('texto', 0), ('link', 2), ('link_externo', 3), ('color', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('imagen', 1), ('botones', 6)]], {})}),
        ),
    ]
