# Generated by Django 6.0.3 on 2026-03-11 13:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0003_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folphomepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 3), ('accesos_rapidos', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('imagen', 2)]], {'template': 'facultad/blocks/hero_slider.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Subí el logo (PNG o SVG preferentemente)', 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('imagen_logo', 4), ('etiqueta', 0), ('url', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'template': 'facultad/blocks/accesos_rapidos.html'})}),
        ),
    ]
