# Generated by Django 6.0.3 on 2026-04-01 13:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0004_remove_noticiapage_elementos_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginaestandar',
            name='cuerpo_tecnicaturas',
            field=wagtail.fields.StreamField([('tecnicatura', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Subir o elegir un PDF/Archivo', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('btn-dark-green', 'Verde Oscuro'), ('btn-light-green', 'Verde Claro'), ('btn-gray', 'Gris')]}), 6: ('wagtail.blocks.StructBlock', [[('texto', 0), ('link', 2), ('link_externo', 3), ('documento', 4), ('color', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('imagen', 1), ('botones', 7)]], {})}),
        ),
    ]
