# Generated by Django 6.0.3 on 2026-03-11 14:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0004_alter_folphomepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folphomepage',
            name='body',
            field=wagtail.fields.StreamField([('carrusel', 5), ('accesos_rapidos', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Elegí la noticia a la que lleva', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('imagen', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'template': 'facultad/blocks/hero_slider.html'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Subí el logo (PNG o SVG preferentemente)', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('imagen_logo', 6), ('etiqueta', 7), ('url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'template': 'facultad/blocks/accesos_rapidos.html'})}),
        ),
    ]
