# Generated by Django 6.0.3 on 2026-03-13 13:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0005_alter_folphomepage_body'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folphomepage',
            name='body',
            field=wagtail.fields.StreamField([('carrusel', 5), ('accesos_rapidos', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Elegí la noticia a la que lleva', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('imagen', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'template': 'facultad/blocks/hero_slider.html'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('imagen_logo', 6), ('etiqueta', 7), ('url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'template': 'facultad/blocks/accesos_rapidos.html'})}),
        ),
        migrations.CreateModel(
            name='PaginaEstandar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitulo', models.CharField(blank=True, max_length=250)),
                ('cuerpo', wagtail.fields.StreamField([('parrafo', 0), ('imagen', 1), ('video', 2)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube'})})),
                ('imagen_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Página Estándar',
            },
            bases=('wagtailcore.page',),
        ),
    ]
