# Generated by Django 6.0.3 on 2026-04-01 13:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0005_alter_paginaestandar_cuerpo_tecnicaturas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginaestandar',
            name='cuerpo_tecnicaturas',
            field=wagtail.fields.StreamField([('tecnicatura', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Plan de Estudios', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Correlativas', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Finales y Reválidas', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('imagen', 1), ('texto_boton_1', 2), ('doc_1', 3), ('texto_boton_2', 4), ('doc_2', 3), ('texto_boton_3', 5), ('doc_3', 3)]], {})}),
        ),
    ]
