# Generated by Django 6.0.3 on 2026-04-06 12:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0006_alter_paginaestandar_cuerpo_tecnicaturas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginaestandar',
            name='cuerpo_tecnicaturas',
            field=wagtail.fields.StreamField([('tecnicatura', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón', 'required': True}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Vincular a una Página', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Vincular a un PDF', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('btn-dark-green', 'Verde Oscuro'), ('btn-light-green', 'Verde Claro'), ('btn-gray', 'Gris')]}), 6: ('wagtail.blocks.StructBlock', [[('texto', 2), ('pagina', 3), ('documento', 4), ('color', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Botones de la tarjeta'}), 8: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('imagen', 1), ('botones', 7)]], {})}),
        ),
    ]
