# Generated by Django 6.0.3 on 2026-03-13 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0006_alter_folphomepage_body_paginaestandar'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiapage',
            name='link_externo',
            field=models.ForeignKey(blank=True, help_text="Si elegís una página acá, el botón 'Leer más' llevará a esa página en lugar de a la noticia misma.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
