# Generated by Django 6.0.3 on 2026-04-09 19:11

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0007_alter_paginaestandar_cuerpo_tecnicaturas'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Curso',
                'verbose_name_plural': 'Categorías de Cursos',
            },
        ),
        migrations.CreateModel(
            name='CursoIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='carrerapage',
            name='plan_estudios',
            field=wagtail.fields.StreamField([('titulo_anio', 0), ('subtitulo_periodo', 1), ('materia', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título de Año'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo de Periodo'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Código', 'max_length': 10, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Nombre de la materia', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Periodicidad (Ej: 1er C.)', 'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'PDF Parte 1 / Único', 'required': False}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'PDF Parte 2 (Solo si tiene /)', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('codigo', 2), ('nombre', 3), ('periodicidad', 4), ('documento', 5), ('documento_2', 6)]], {'label': 'Materia'})}),
        ),
        migrations.CreateModel(
            name='CursoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descripcion_corta', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('categorias', modelcluster.fields.ParentalManyToManyField(blank=True, to='facultad.categoriacurso')),
                ('imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
