# Generated by Django 6.0.3 on 2026-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0007_noticiapage_link_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiapage',
            name='prioridad',
            field=models.IntegerField(default=10, help_text='1 es lo más importante (aparece primero). 10 es lo normal.'),
        ),
    ]
