# Generated by Django 6.0.3 on 2026-04-09 19:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0008_categoriacurso_cursoindexpage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursopage',
            old_name='imagen',
            new_name='imagen_afiche',
        ),
        migrations.AddField(
            model_name='cursopage',
            name='arancel_no_socios',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='arancel_socios',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='cupo_disponible',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='docentes',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 18 Sesiones', max_length=255),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='forma_pago',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='horario',
            field=models.CharField(blank=True, help_text='Ej: De 9:00 a 16:00hs', max_length=255),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='link_programa',
            field=models.URLField(blank=True, help_text='URL para descargar el PDF del programa'),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='matricula',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='modalidad_detalle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='modalidad_resumen',
            field=models.CharField(blank=True, help_text='Ej: Teórico con práctica clínica', max_length=255),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='requisitos',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cursopage',
            name='descripcion_corta',
            field=models.TextField(blank=True, help_text='Se muestra en la card del índice'),
        ),
    ]
