# Generated by Django 6.0.3 on 2026-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0008_noticiapage_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiapage',
            name='ancho',
            field=models.CharField(choices=[('col-md-4', 'Chica (1/3 de línea)'), ('col-md-8', 'Mediana (2/3 de línea)'), ('col-12', 'Grande (Toda la línea)')], default='col-md-4', help_text='Elegí cuánto espacio ocupa esta noticia en la Home', max_length=20),
        ),
    ]
