# Generated by Django 6.0.3 on 2026-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0009_noticiapage_ancho'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiapage',
            name='mostrar_texto_en_home',
            field=models.BooleanField(default=True, help_text='Si se desmarca, en la Home solo se verá la imagen (ideal para banners diseñados).'),
        ),
    ]
