# Generated by Django 6.0.3 on 2026-03-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0010_noticiapage_mostrar_texto_en_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiapage',
            name='convertir_en_popup',
            field=models.BooleanField(default=False, help_text='Si se marca, esta noticia aparecerá como un anuncio emergente al cargar la Home.'),
        ),
    ]
