# Generated by Django 6.0.3 on 2026-03-16 13:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0012_noticiapage_boton_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginaestandar',
            name='boton_accion',
            field=wagtail.fields.StreamField([('boton', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ej: Descargar PDF', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Pegá el link aquí', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'O elegí una página interna', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ej: fa-file-pdf', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Logo chiquito', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('texto', 0), ('url_o_archivo', 1), ('documento', 2), ('icono_fontawesome', 3), ('imagen_logo', 4)]], {'icon': 'link'})}),
        ),
    ]
