# Generated by Django 6.0.3 on 2026-03-16 14:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0014_alter_noticiapage_boton_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiapage',
            name='boton_accion',
            field=wagtail.fields.StreamField([('boton', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ej: Descargar Programa', 'required': True}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Subí o elegí un PDF/Doc', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'O pegá un link si el archivo es externo', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ej: fa-file-pdf', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('texto', 0), ('archivo', 1), ('url_externa', 2), ('icono_fontawesome', 3), ('imagen_logo', 4)]], {'icon': 'doc-full'})}),
        ),
    ]
