# Generated by Django 6.0.3 on 2026-03-16 14:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0015_alter_noticiapage_boton_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiapage',
            name='boton_accion',
            field=wagtail.fields.StreamField([('boton', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón', 'required': True}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Subir/Elegir Documento', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Link Externo', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'placeholder': 'fa-file-pdf', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('texto', 0), ('archivo', 1), ('url_externa', 2), ('icono_fontawesome', 3), ('imagen_logo', 4)]], {'icon': 'doc-full'})}),
        ),
    ]
