# Generated by Django 6.0.3 on 2026-04-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0015_revistasindexpage_alter_noticiapage_prioridad_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revistapage',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='revistapage',
            name='portada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
