# Generated by Django 6.0.3 on 2026-04-17 11:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0016_remove_revistapage_fecha_publicacion_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revistasindexpage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='cursopage',
            name='bibliografia',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Bibliografía'),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='es_arancelado',
            field=models.BooleanField(default=True, help_text='Marcar si el curso tiene costo'),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='evaluacion',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Formas de Evaluación'),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='precio',
            field=models.CharField(blank=True, help_text='Ej: $5000 o Gratuito', max_length=100),
        ),
        migrations.AddField(
            model_name='cursopage',
            name='programa_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.DeleteModel(
            name='RevistaPage',
        ),
        migrations.DeleteModel(
            name='RevistasIndexPage',
        ),
    ]
