# Generated by Django 6.0.3 on 2026-03-16 14:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0016_alter_noticiapage_boton_accion'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo_carrera', models.CharField(default='Carrera Odontología', max_length=255)),
                ('plan_estudios', wagtail.fields.StreamField([('titulo_anio', 0), ('subtitulo_periodo', 1), ('materia', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'group': 'Estructura', 'label': 'Título de Año'}), 1: ('wagtail.blocks.CharBlock', (), {'group': 'Estructura', 'label': 'Subtítulo de Periodo'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Código', 'max_length': 10, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Nombre de la materia', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Periodicidad (Ej: 1er C.)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('codigo', 2), ('nombre', 3), ('periodicidad', 4)]], {'group': 'Contenido'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
