# Generated by Django 6.0.3 on 2026-03-17 15:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0017_carrerapage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paginaestandar',
            options={},
        ),
        migrations.AlterField(
            model_name='carrerapage',
            name='plan_estudios',
            field=wagtail.fields.StreamField([('titulo_anio', 0), ('subtitulo_periodo', 1), ('materia', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título de Año'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo de Periodo'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Código', 'max_length': 10, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Nombre de la materia', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Periodicidad (Ej: 1er C.)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('codigo', 2), ('nombre', 3), ('periodicidad', 4)]], {'label': 'Materia'})}),
        ),
        migrations.AlterField(
            model_name='folphomepage',
            name='body',
            field=wagtail.fields.StreamField([('carrusel', 5), ('accesos_rapidos', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('imagen', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'template': 'facultad/blocks/hero_slider.html'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('imagen_logo', 6), ('etiqueta', 7), ('url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'template': 'facultad/blocks/accesos_rapidos.html'})}),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='ancho',
            field=models.CharField(choices=[('col-md-4', 'Chica'), ('col-md-8', 'Mediana'), ('col-12', 'Grande')], default='col-md-4', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='boton_accion',
            field=wagtail.fields.StreamField([('boton', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('texto', 0), ('archivo', 1), ('url_externa', 2), ('icono_fontawesome', 3), ('imagen_logo', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='convertir_en_popup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='cuerpo',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='link_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='mostrar_texto_en_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='prioridad',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='paginaestandar',
            name='boton_accion',
            field=wagtail.fields.StreamField([('boton', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('texto', 0), ('url_o_archivo', 1), ('documento', 2), ('icono_fontawesome', 0), ('imagen_logo', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='paginaestandar',
            name='cuerpo',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
