# Generated by Django 6.0.3 on 2026-04-17 13:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0017_remove_revistasindexpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursopage',
            name='programa_texto',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Programa (Texto)'),
        ),
    ]
