# Generated by Django 6.0.3 on 2026-04-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0018_cursopage_programa_texto'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo_boton_boceto', models.CharField(default='Información General', help_text='Nombre del segundo boton', max_length=50)),
                ('link_boton_boceto', models.URLField(blank=True, help_text='Link provisional (boceto)')),
                ('imagen_fondo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('pagina_plan_estudios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Carátula de Carrera',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticiaClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_click', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_locales', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Clic de Noticia',
            },
        ),
    ]
