# Generated by Django 6.0.3 on 2026-03-20 13:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0018_alter_paginaestandar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiapage',
            name='elementos_extra',
            field=wagtail.fields.StreamField([('p', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {})}, null=True),
        ),
    ]
