# Generated by Django 6.0.3 on 2026-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0019_noticiapage_elementos_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiapage',
            name='video_url',
            field=models.URLField(blank=True, help_text='Pegá acá el link de YouTube (ej: https://www.youtube.com/watch?v=...) para que aparezca al final de la noticia.', null=True),
        ),
    ]
