# Generated by Django 6.0.3 on 2026-03-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0020_noticiapage_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginaestandar',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link de YouTube', null=True),
        ),
    ]
