# Generated by Django 6.0.3 on 2026-03-20 16:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0021_paginaestandar_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginaestandar',
            name='elementos_extra',
            field=wagtail.fields.StreamField([('p', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {})}, null=True),
        ),
    ]
