# Generated by Django 6.0.3 on 2026-03-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0022_paginaestandar_elementos_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginaestandar',
            name='elementos_extra',
        ),
    ]
